name: all_for_sports
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2


dependencies:
  flutter:
    sdk: flutter
  geolocator: ^13.0.1
  http: ^1.2.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  provider: ^6.1.2
  mobile_scanner: ^5.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
